/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DojoCard {
    }
    interface DojoSlider {
        "thumbSize": number;
    }
}
declare global {
    interface HTMLDojoCardElement extends Components.DojoCard, HTMLStencilElement {
    }
    var HTMLDojoCardElement: {
        prototype: HTMLDojoCardElement;
        new (): HTMLDojoCardElement;
    };
    interface HTMLDojoSliderElement extends Components.DojoSlider, HTMLStencilElement {
    }
    var HTMLDojoSliderElement: {
        prototype: HTMLDojoSliderElement;
        new (): HTMLDojoSliderElement;
    };
    interface HTMLElementTagNameMap {
        "dojo-card": HTMLDojoCardElement;
        "dojo-slider": HTMLDojoSliderElement;
    }
}
declare namespace LocalJSX {
    interface DojoCard {
    }
    interface DojoSlider {
        "thumbSize"?: number;
    }
    interface IntrinsicElements {
        "dojo-card": DojoCard;
        "dojo-slider": DojoSlider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dojo-card": LocalJSX.DojoCard & JSXBase.HTMLAttributes<HTMLDojoCardElement>;
            "dojo-slider": LocalJSX.DojoSlider & JSXBase.HTMLAttributes<HTMLDojoSliderElement>;
        }
    }
}
