/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DojoSlider {
    }
}
declare global {
    interface HTMLDojoSliderElement extends Components.DojoSlider, HTMLStencilElement {
    }
    var HTMLDojoSliderElement: {
        prototype: HTMLDojoSliderElement;
        new (): HTMLDojoSliderElement;
    };
    interface HTMLElementTagNameMap {
        "dojo-slider": HTMLDojoSliderElement;
    }
}
declare namespace LocalJSX {
    interface DojoSlider {
    }
    interface IntrinsicElements {
        "dojo-slider": DojoSlider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dojo-slider": LocalJSX.DojoSlider & JSXBase.HTMLAttributes<HTMLDojoSliderElement>;
        }
    }
}
